[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Financial Trading: Investigating the Applications and Impacts of Intelligent Technologies in Stock Market Trading"
